name: Trigger Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    environment: 
      name: CI Workflow
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Started!'