# This is a basic workflow to help you get started with Actions

name: TEST

on:
  workflow_run:
    workflows: ["Trigger Test"]
    types: 
      - completed
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Use Github Secret
        run: echo ${{secrets.SECRET_NAME}}

  
